### PR TITLE
Backport new tests from WebAssembly/spec master

### PR DESCRIPTION
**Pull request by gumb0**

### CODE REVIEW

**Comment by chfast** [comment]
Are you sure you want to keep the merge commit on the "backported" branch?

**Comment by gumb0** [comment]
> Are you sure you want to keep the merge commit on the "backported" branch?

Is your preference not to?

**Comment by chfast** [comment]
Yes, because upstream is also using merge-free git style.

**Comment by gumb0** [comment]
Removed merge commit and changed the tag.

**Pull request merged**
